// src/utils/fileStorage.ts
// Utility for handling real client-side file uploads, data URL conversions, and downloads across all portals

/**
 * Reads a File object from input / drop into a base64 Data URL string
 */
export function readFileAsDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      resolve(reader.result as string);
    };
    reader.onerror = (err) => {
      reject(err);
    };
    reader.readAsDataURL(file);
  });
}

/**
 * Formats byte size into human readable string (e.g. 245 KB, 1.4 MB)
 */
export function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

/**
 * Creates a clean downloadable default text/PDF representation if no dataUrl is present
 */
export function generateSampleResumeDataUrl(studentName: string, programme: string, skills: string[]): string {
  const content = `=====================================================
RV UNIVERSITY - OFFICIAL PLACEMENT DOSSIER
=====================================================

CANDIDATE: ${studentName.toUpperCase()}
PROGRAMME: ${programme}
ACADEMIC YEAR: 2026-2027
UNIVERSITY: RV University, Bengaluru

-----------------------------------------------------
TECHNICAL SKILLS & CORE COMPETENCIES
-----------------------------------------------------
${skills.join(' • ')}

-----------------------------------------------------
ACADEMIC SUMMARY
-----------------------------------------------------
Cumulative CGPA: 8.42 / 10.0
Backlogs: 0 Active
CAR Verified: YES (Office of Corporate & Alumni Relations)

-----------------------------------------------------
PLACEMENT DISCLOSURE
-----------------------------------------------------
This document is generated by the RVU Career Management Portal
for campus recruitment and enterprise employer verification.
=====================================================`;

  return `data:text/plain;charset=utf-8,${encodeURIComponent(content)}`;
}

/**
 * Triggers a real browser file download for a given file name and data URL / URL
 */
export function triggerFileDownload(fileName: string, dataUrl?: string, fallbackContent?: string): void {
  const downloadUrl = dataUrl || (fallbackContent 
    ? `data:text/plain;charset=utf-8,${encodeURIComponent(fallbackContent)}`
    : `data:text/plain;charset=utf-8,${encodeURIComponent(`Document: ${fileName}\nSource: RVU Placement Portal`)}`);

  const anchor = document.createElement('a');
  anchor.href = downloadUrl;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
}
